// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsZ36SVmk2jZrDF8vMlwPbCSxn43Drjv4',
    appId: '1:202045607116:web:6faef51a06c34912ad8669',
    messagingSenderId: '202045607116',
    projectId: 'open-codeword',
    authDomain: 'open-codeword.firebaseapp.com',
    storageBucket: 'open-codeword.firebasestorage.app',
    measurementId: 'G-958SRET164',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL74tYRMEXyRmQgBnYSTayTTFSk--cfko',
    appId: '1:202045607116:android:b332c1ae9baa7935ad8669',
    messagingSenderId: '202045607116',
    projectId: 'open-codeword',
    storageBucket: 'open-codeword.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA53-s9Xp-RlWHsCsrvS4rw78MQ0Y2q2uI',
    appId: '1:202045607116:ios:d6205690b65adca6ad8669',
    messagingSenderId: '202045607116',
    projectId: 'open-codeword',
    storageBucket: 'open-codeword.firebasestorage.app',
    iosBundleId: 'com.example.codeword',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA53-s9Xp-RlWHsCsrvS4rw78MQ0Y2q2uI',
    appId: '1:202045607116:ios:d6205690b65adca6ad8669',
    messagingSenderId: '202045607116',
    projectId: 'open-codeword',
    storageBucket: 'open-codeword.firebasestorage.app',
    iosBundleId: 'com.example.codeword',
  );
}
